# Generated by Django 2.2.5 on 2019-09-07 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(help_text='品牌', max_length=10)),
                ('code', models.CharField(help_text='店铺编号', max_length=10, null=True)),
                ('name', models.CharField(help_text='店铺名称', max_length=100, null=True)),
                ('address', models.CharField(help_text='地址', max_length=300, null=True)),
                ('ip', models.GenericIPAddressField(help_text='IP', null=True, protocol='IPv4')),
                ('ap', models.PositiveSmallIntegerField(help_text='AP 数量', null=True)),
                ('contacts', models.TextField(help_text='联系人', null=True)),
                ('equipment_arrival_date', models.DateField(help_text='设备到店日期', null=True)),
                ('completion_date', models.DateField(help_text='工程完工日期', null=True)),
                ('expected_installation_date', models.DateField(help_text='预计安装日期', null=True)),
                ('Opening_date', models.DateField(help_text='开店日期', null=True)),
                ('engineering_head', models.CharField(help_text='工程部负责人', max_length=100, null=True)),
                ('firewall_type', models.CharField(help_text='防火墙类型', max_length=20)),
                ('status', models.CharField(choices=[('1', '筹备'), ('2', '正常'), ('3', '护肤'), ('4', '闭店')], help_text='状态', max_length=10)),
                ('ps', models.TextField(help_text='备注', max_length=300, null=True)),
            ],
        ),
    ]
