# Generated by Django 2.0.2 on 2019-10-22 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=10, verbose_name='品牌')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='店铺编号')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='店铺名称')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='地址')),
                ('ip', models.GenericIPAddressField(null=True, protocol='IPv4', verbose_name='IP')),
                ('ap', models.PositiveSmallIntegerField(null=True, verbose_name='AP 数量')),
                ('contacts', models.TextField(null=True, verbose_name='联系人')),
                ('equipment_arrival_date', models.DateField(null=True, verbose_name='设备到店日期')),
                ('completion_date', models.DateField(null=True, verbose_name='工程完工日期')),
                ('expected_installation_date', models.DateField(null=True, verbose_name='预计安装日期')),
                ('Opening_date', models.DateField(null=True, verbose_name='开店日期')),
                ('engineering_head', models.CharField(max_length=100, null=True, verbose_name='工程部负责人')),
                ('firewall_type', models.CharField(max_length=20, verbose_name='防火墙类型')),
                ('status', models.CharField(choices=[('1', '筹备'), ('2', '正常'), ('3', '护肤'), ('4', '闭店')], max_length=10, verbose_name='状态')),
                ('ps', models.TextField(max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '店铺',
            },
        ),
    ]
