# Generated by Django 2.0.2 on 2019-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0002_auto_20191209_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecomment',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='storecomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='备注日期'),
        ),
    ]
