# Generated by Django 2.0.2 on 2020-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0003_auto_20191209_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinformation',
            name='guest_wifi',
            field=models.BooleanField(default=False, verbose_name='客用wifi'),
        ),
    ]
