# Generated by Django 2.0.2 on 2020-04-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0005_storeinformation_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinformation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
