# Generated by Django 2.0.2 on 2020-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0006_auto_20200409_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinformation',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='闭店日期'),
        ),
    ]
