# Generated by Django 2.0.2 on 2020-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0007_storeinformation_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinformation',
            name='top_star',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='星标'),
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='status',
            field=models.CharField(choices=[('1', '筹备'), ('5', '筹备-施工'), ('6', '筹备-发货'), ('7', '筹备-安装'), ('8', '筹备-完工'), ('2', '正常'), ('3', '护肤'), ('4', '闭店')], max_length=10, verbose_name='状态'),
        ),
    ]
